CREATE TABLE `projects` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`charity_id` integer NOT NULL,
	`title` text NOT NULL,
	`description` text NOT NULL,
	`meta_cid` text NOT NULL,
	`zakat_mode` integer DEFAULT false NOT NULL,
	`asnaf_tag` text,
	`contract_template` text NOT NULL,
	`total_amount` real NOT NULL,
	`funded_balance` real DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'active' NOT NULL,
	`blockchain_tx_hash` text,
	`contract_address` text,
	`deadline` text,
	`deadline_enabled` integer DEFAULT false,
	`created_at` text NOT NULL,
	`updated_at` text,
	FOREIGN KEY (`charity_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
